<?php
/**
 * sysMonDash
 *
 * @author    nuxsmin
 * @link      http://cygnux.org
 * @copyright 2012-2016 Rubén Domínguez nuxsmin@cygnux.org
 *
 * This file is part of sysMonDash.
 *
 * sysMonDash is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * sysMonDash is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with sysMonDash.  If not, see <http://www.gnu.org/licenses/>.
 */

use SMD\Backend\Event\EventStateTrigger;
use SMD\Core\Config;
use SMD\Core\ConfigBackend;
use SMD\Core\Language;

$i = 0;
$j = 0;
$k = 0;
$l = 0;
$m = 0;
$n = 0;
?>

<fieldset>
    <legend>
        <i class="fa fa-caret-up container-state" data-container="backends-config-container"></i>
        Backends
    </legend>
    <div id="backends-config-container" class="flex-wrapper" aria-expanded="true">
        <div class="pure-menu pure-menu-horizontal">
            <ul class="pure-menu-list">
                <li class="pure-menu-item pure-menu-has-children pure-menu-allow-hover">
                    <a href="#" id="menuLinkBackends" class="pure-menu-link pure-menu-selected">
                        <i class="fa fa-plus-circle"></i>
                        <?php echo Language::t('Añadir Backend'); ?>
                    </a>
                    <ul class="pure-menu-children">
                        <li class="pure-menu-item">
                            <a class="pure-menu-link add-backend" href="#" data-type="livestatus">Livestatus</a>
                        </li>
                        <li class="pure-menu-item">
                            <a class="pure-menu-link add-backend" href="#" data-type="checkmklivestatus">Check_MK</a>
                        </li>
                        <li class="pure-menu-item">
                            <a class="pure-menu-link add-backend" href="#" data-type="status">Status</a>
                        </li>
                        <li class="pure-menu-item">
                            <a class="pure-menu-link add-backend" href="#" data-type="zabbix">Zabbix</a>
                        </li>
                        <li class="pure-menu-item">
                            <a class="pure-menu-link add-backend" href="#" data-type="smd">sysMonDash</a>
                        </li>
                        <li class="pure-menu-item">
                            <a class="pure-menu-link add-backend" href="#" data-type="dummy">Dummy</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>

        <?php foreach (Config::getConfig()->getBackend() as $Backend): ?>
            <?php if ($Backend->getType() === ConfigBackend::TYPE_STATUS): ?>
                <div class="backendStatus backendConfig">
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Alias'); ?></label>
                        <input type="text" name="backend[status][<?php echo $i; ?>][alias]"
                               class="pure-input-1-2"
                               value="<?php echo $Backend->getAlias(); ?>"/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Ruta archivo status.dat'); ?></label>
                        <input type="text"
                               name="backend[status][<?php echo $i; ?>][path]"
                               class="pure-input-1-2 backend_status_file"
                               value="<?php echo $Backend->getPath(); ?>"
                               placeholder="/var/lib/icinga/status.dat" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Activo'); ?></label>
                        <input type="checkbox"
                               name="backend[status][<?php echo $i; ?>][active]" <?php echo ($Backend->isActive()) ? 'checked' : ''; ?>/>
                    </div>
                    <div class="buttons">
                        <button type="button" class="button-error pure-button backendDelete">
                            <i class="fa fa-minus-circle"></i>
                            <?php echo Language::t('Eliminar'); ?>
                        </button>
                    </div>
                </div>
                <?php $i++; ?>
            <?php elseif ($Backend->getType() === ConfigBackend::TYPE_LIVESTATUS): ?>
                <div class="backendLivestatus backendConfig">
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Alias'); ?></label>
                        <input type="text" name="backend[livestatus][<?php echo $j; ?>][alias]"
                               class="pure-input-1-2"
                               value="<?php echo $Backend->getAlias(); ?>"/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Ruta socket livestatus'); ?></label>
                        <input type="text"
                               name="backend[livestatus][<?php echo $j; ?>][path]"
                               class="pure-input-1-2 backend_livestatus_file"
                               value="<?php echo $Backend->getPath(); ?>"
                               placeholder="/var/lib/icinga/rw/live" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Activo'); ?></label>
                        <input type="checkbox"
                               name="backend[livestatus][<?php echo $j; ?>][active]" <?php echo ($Backend->isActive()) ? 'checked' : ''; ?>/>
                    </div>
                    <div class="buttons">
                        <button type="button" class="button-error pure-button backendDelete">
                            <i class="fa fa-minus-circle"></i>
                            <?php echo Language::t('Eliminar'); ?>
                        </button>
                    </div>
                </div>
                <?php $j++; ?>
            <?php elseif ($Backend->getType() === ConfigBackend::TYPE_ZABBIX): ?>
                <div class="backendZabbix backendConfig">
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Alias'); ?></label>
                        <input type="text" name="backend[zabbix][<?php echo $k; ?>][alias]"
                               class="pure-input-1-2"
                               value="<?php echo $Backend->getAlias(); ?>"/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('URL API de Zabbix'); ?></label>
                        <input type="text"
                               name="backend[zabbix][<?php echo $k; ?>][url]"
                               class="pure-input-1-2 backend_zabbix_url"
                               value="<?php echo $Backend->getUrl(); ?>"
                               placeholder="http://foo.bar/zabbix/api_jsonrpc.php" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Versión API de Zabbix'); ?></label>
                        <select class="backend_zabbix_version"
                                name="backend[zabbix][<?php echo $k; ?>][version]"
                                data-selected="<?php echo $Backend->getVersion(); ?>" required>
                            <option value="220">2.2</option>
                            <option value="240">2.4</option>
                        </select>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Usuario API de Zabbix'); ?></label>
                        <input type="text" class="backend_zabbix_user"
                               name="backend[zabbix][<?php echo $k; ?>][user]"
                               value="<?php echo $Backend->getUser(); ?>" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Clave API de Zabbix'); ?></label>
                        <input type="password" class="backend_zabbix_pass"
                               name="backend[zabbix][<?php echo $k; ?>][pass]"
                               value="<?php echo $Backend->getPass(); ?>" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Nivel mínimo de eventos'); ?></label>
                        <select class="backend_zabbix_level"
                                name="backend[zabbix][<?php echo $k; ?>][level]"
                                data-selected="<?php echo $Backend->getLevel(); ?>" required>
                            <?php foreach (EventStateTrigger::getStates() as $level => $detail): ?>
                                <option
                                        value="<?php echo $level; ?>"><?php echo Language::t($detail[0]); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Activo'); ?></label>
                        <input type="checkbox"
                               name="backend[zabbix][<?php echo $k; ?>][active]" <?php echo ($Backend->isActive()) ? 'checked' : ''; ?>/>
                    </div>
                    <div class="buttons">
                        <button type="button" class="button-secondary pure-button backendCheckZabbix">
                            <i class="fa fa-check-circle"></i>
                            <?php echo Language::t('Comprobar'); ?>
                        </button>
                        <button type="button" class="button-error pure-button backendDelete">
                            <i class="fa fa-minus-circle"></i>
                            <?php echo Language::t('Eliminar'); ?>
                        </button>
                    </div>
                </div>
                <?php $k++; ?>
            <?php elseif ($Backend->getType() === ConfigBackend::TYPE_SMD): ?>
                <div class="backendSMD backendConfig">
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Alias'); ?></label>
                        <input type="text" name="backend[smd][<?php echo $l; ?>][alias]"
                               class="pure-input-1-2"
                               value="<?php echo $Backend->getAlias(); ?>"/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('URL API sysMonDash'); ?></label>
                        <input type="text"
                               name="backend[smd][<?php echo $l; ?>][url]"
                               class="pure-input-1-2 backend_smd_url"
                               value="<?php echo $Backend->getUrl(); ?>"
                               placeholder="http://foo.bar/sysMonDash/api.php" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Token'); ?></label>
                        <input type="text" name="backend[smd][<?php echo $l; ?>][token]"
                               class="pure-input-1-2 backend_smd_token"
                               value="<?php echo $Backend->getToken(); ?>"/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Activo'); ?></label>
                        <input type="checkbox"
                               name="backend[smd][<?php echo $l; ?>][active]" <?php echo ($Backend->isActive()) ? 'checked' : ''; ?>/>
                    </div>
                    <div class="buttons">
                        <button type="button" class="button-secondary pure-button backendCheckSMD">
                            <i class="fa fa-check-circle"></i>
                            <?php echo Language::t('Comprobar'); ?>
                        </button>
                        <button type="button" class="button-error pure-button backendDelete">
                            <i class="fa fa-minus-circle"></i>
                            <?php echo Language::t('Eliminar'); ?>
                        </button>
                    </div>
                </div>
                <?php $l++; ?>
            <?php elseif ($Backend->getType() === ConfigBackend::TYPE_CHECKMK): ?>
                <div class="backendCheckMK backendConfig">
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Alias'); ?></label>
                        <input type="text" name="backend[checkmk][<?php echo $m; ?>][alias]"
                               class="pure-input-1-2"
                               value="<?php echo $Backend->getAlias(); ?>"/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Ruta socket Check_MK'); ?></label>
                        <input type="text"
                               name="backend[checkmk][<?php echo $m; ?>][path]"
                               class="pure-input-1-2 backend_checkmk_file"
                               value="<?php echo $Backend->getPath(); ?>"
                               placeholder="/omd/sites/mysite/tmp/run/live | http://omdserver:6557"
                               required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Activo'); ?></label>
                        <input type="checkbox"
                               name="backend[checkmk][<?php echo $m; ?>][active]" <?php echo ($Backend->isActive()) ? 'checked' : ''; ?>/>
                    </div>
                    <div class="buttons">
                        <button type="button" class="button-error pure-button backendDelete">
                            <i class="fa fa-minus-circle"></i>
                            <?php echo Language::t('Eliminar'); ?>
                        </button>
                    </div>
                </div>
                <?php $m++; ?>
            <?php elseif ($Backend->getType() === ConfigBackend::TYPE_DUMMY): ?>
                <div class="backendDummy backendConfig">
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Alias'); ?></label>
                        <input type="text" name="backend[dummy][<?php echo $n; ?>][alias]"
                               class="pure-input-1-2"
                               value="<?php echo $Backend->getAlias(); ?>"/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Ruta archivo JSON'); ?></label>
                        <input type="text"
                               name="backend[dummy][<?php echo $n; ?>][path]"
                               class="pure-input-1-2 backend_dummy_file"
                               value="<?php echo $Backend->getPath(); ?>"
                               placeholder="/etc/sysMonDash/dummy_backend.json" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('URL imagen'); ?></label>
                        <input type="text"
                               name="backend[dummy][<?php echo $n; ?>][image]"
                               class="pure-input-1-2 backend_dummy_image"
                               value="<?php echo $Backend->getImagePath(); ?>"
                               placeholder="/var/www/html/smd/assets/dummy.png" required/>
                    </div>
                    <div class="pure-control-group">
                        <label><?php echo Language::t('Activo'); ?></label>
                        <input type="checkbox"
                               name="backend[dummy][<?php echo $n; ?>][active]" <?php echo ($Backend->isActive()) ? 'checked' : ''; ?>/>
                    </div>
                    <div class="buttons">
                        <button type="button" class="button-error pure-button backendDelete">
                            <i class="fa fa-minus-circle"></i>
                            <?php echo Language::t('Eliminar'); ?>
                        </button>
                    </div>
                </div>
                <?php $n++; ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</fieldset>